server:
  port: ${port:8504}

security.basic.enabled: false

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}

spring:
  application:
    name: Sleuth
