server:
  port: 8501

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${hostname:eureka-server}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
